services:
  backend:
    build: ./code/backend
    container_name: backend
    restart: unless-stopped
    networks: [app-net]
    environment:
      - PORT=4000
      - AMADEUS_API_KEY=z2e4WZRwwip2WekklcWBaahkQLjDd0xD
      - AMADEUS_API_SECRET=fuXxSTPNh5o1jxvY
    expose:
      - '4000'

  frontend:
    build: ./code/frontend
    container_name: frontend
    restart: unless-stopped
    networks: [app-net]
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=http://backend:4000
    expose:
      - '3000'

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt
      - certs-data:/var/lib/letsencrypt
    networks: [app-net]

networks:
  app-net:
    driver: bridge

volumes:
  certs:
  certs-data:
