services:
  backend:
    build: ./code/backend
    container_name: backend
    restart: unless-stopped
    networks: [app-net]
    environment:
      - NODE_ENV=production
      - AMADEUS_CLIENT_ID
      - AMADEUS_CLIENT_SECRET
    expose:
      - '4000'

  frontend:
    build: ./code/frontend
    container_name: frontend
    restart: unless-stopped
    networks: [app-net]
    expose:
      - '3000'

  nginx:
    image: nginx:1.27-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flights_app-net
    depends_on:
      - frontend
      - backend

networks:
  app-net:
    driver: bridge

volumes:
  certs:
  certs-data:
